spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start_only

papers:
  directory: C:\\papers

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
